spring:
  datasource:
    driver-class: com.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/plan_api
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
     
plan-api:
 messages:
  planSaveSucc: Plan Saved Successfully
  planSaveFail: Plan Save Failed
  planUpdateSucc: Plan Updated Successfully
  planUpdateFail: Plan Update Failed
  planDeleteSucc: Plan Deleted Successfully
  planDeleteFail: Plan Delete Failed
  planStatusChangeSucc: Plan Status Changed Successfully
  planStatusChangeFail: Plan Status Change Failed
  
